steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/visiontalk', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/visiontalk']
images:
- 'gcr.io/$PROJECT_ID/visiontalk'
options:
  logging: CLOUD_LOGGING_ONLY
